import type { Metadata } from "next";
import styles from "./page.module.css";

import Resume from "@/components/Resume";

export const metadata: Metadata = {
  title: "My Resume",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <main className={styles.main}>
      <div className={styles.page}>
        <Resume />
      </div>
    </main>
  );
}
